### ISSUE TITLE
Discriminating

### ISSUE THREAD

**Issue by julfr** [OFAI/million-post-corpus#1]
How could I get a `.csv` file with only posts re. Discrimination? 
Thanks in advance

**Comment by dietmar** [comment]
The way I would do it:
* Load the data into a pandas DataFrame `df` by using `pandas.read_sql()` with an appropriate SQL query. See the database schema at https://github.com/OFAI/million-post-corpus/blob/master/database_schema.md
* Save the result to a CSV file using `df.to_csv()`

You can probably also achieve the same using sqlite3 only, and a shell redirect.

**Comment by julfr** [comment]
> The way I would do it:
> 
> * Load the data into a pandas DataFrame `df` by using `pandas.read_sql()` with an appropriate SQL query. See the database schema at https://github.com/OFAI/million-post-corpus/blob/master/database_schema.md
> * Save the result to a CSV file using `df.to_csv()`
> 
> You can probably also achieve the same using sqlite3 only, and a shell redirect.

I'm a bit confused, could yoe help me please:
Could you please provide how do I connect to the database? Which path is correct? Does it look like `db = '../million-post-corpus/corpus.sqlite3'`? What would be the whole corect path then?
